name: scq
channels:
  - conda-forge
dependencies:
  - python=3.10
  - qfit               # esto es su paso 3
  - scqubits           # esto es lo que pide el workshop
  - jupyterlab         # tus extras
  - ipykernel
  - ipywidgets
